name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to github-pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          base_href: /evoting-explorer/
